In [16]:
import joblib
import numpy as np

In [24]:
scale = joblib.load('scaling.pkl')

In [25]:
scale.transform([[132,221,321,23]])

/Users/noordeen/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[134.24755406, 578.10124157, 171.3090465 ,  27.66058594]])

In [14]:
imputation = joblib.load('impute.pkl')

In [18]:
imputation.transform([[132,np.NaN,321,23]])

/Users/noordeen/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(


array([[132.        ,   3.07307692, 321.        ,  23.        ]])

In [19]:
encode = joblib.load('encode.pkl')

In [20]:
encode.transform([['lily']])

/Users/noordeen/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1])

In [21]:
encode.transform([['rose']])

array([2])

In [22]:
encode.transform([['jasmine']])

array([0])

In [23]:
encode.transform([['']])

ValueError: y contains previously unseen labels: 'jasminee'

In [26]:
pipe = joblib.load('pipe.pkl')

In [30]:
pipe.predict([[np.NaN,np.NaN,np.NaN,21]])

array([2])

In [32]:
best_model = joblib.load('best_model_pipe.pkl')

In [34]:
best_model.predict([[23,43,np.NaN,2]])

array([2])