In [119]:
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.datasets import load_iris
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
import joblib

In [4]:
data = load_iris()

In [98]:
X = data['data']
#X = pd.DataFrame(X,columns = data['feature_names'])

In [99]:
X.shape

(150, 4)

In [56]:
flower = ['rose','jasmine','lily']

In [58]:
new_col = []
for i in range(0,50):
    new_col.append(flower)

In [63]:
X['flower'] = [xs for x in new_col for xs in x]

In [76]:
y = data['target']

In [77]:
X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [78]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [100]:
train_X,test_X,train_y,test_y = train_test_split(X,y,test_size = 0.3, random_state = 12,stratify= y)

In [138]:
train_X

array([[6.6, 3. , 4.4, 1.4],
       [6.9, 3.2, 5.7, 2.3],
       [4.4, 2.9, 1.4, 0.2],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.7, 5.1, 1.6],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3. , 1.3, 0.2],
       [6.2, 2.2, 4.5, 1.5],
       [7.2, 3.2, 6. , 1.8],
       [5.8, 2.7, 5.1, 1.9],
       [5.7, 3. , 4.2, 1.2],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.1, 4.7, 1.5],
       [5.1, 2.5, 3. , 1.1],
       [5.1, 3.4, 1.5, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [7.7, 3.8, 6.7, 2.2],
       [5.6, 3. , 4.1, 1.3],
       [6.7, 3.3, 5.7, 2.5],
       [5.7, 2.5, 5. , 2. ],
       [6.3, 2.5, 5. , 1.9],
       [5.7, 2.8, 4.1, 1.3],
       [5.4, 3.9, 1.3, 0.4],
       [5. , 3.2, 1.2, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [5.5, 4.2, 1.4, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.9, 3. , 5.1, 1.8],
       [4.9, 3.6, 1.4, 0.1],
       [6.4, 2.7, 5.3, 1.9],
       [4.9, 3. , 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6. , 2.2, 5. , 1.5],
       [4.4, 3

In [147]:
scale = StandardScaler()

In [150]:
scale.fit(train_X)

StandardScaler()

In [151]:
scale.transform(train_X)

array([[ 1.00614742, -0.15874243,  0.38865271,  0.27908984],
       [ 1.39550422,  0.27988797,  1.14544437,  1.48338159],
       [-1.84913579, -0.37805763, -1.35778957, -1.32663251],
       [ 1.13593302, -0.15874243,  0.73794117,  0.68052042],
       [ 0.22743381, -0.81668802,  0.79615591,  0.54671023],
       [-1.71935019, -1.69394882, -1.41600431, -1.19282231],
       [-1.84913579, -0.15874243, -1.41600431, -1.32663251],
       [ 0.48700502, -1.91326402,  0.44686745,  0.41290003],
       [ 1.78486102,  0.27988797,  1.3200886 ,  0.81433062],
       [-0.03213739, -0.81668802,  0.79615591,  0.94814081],
       [-0.16192299, -0.15874243,  0.27222323,  0.01146945],
       [ 0.61679062, -0.81668802,  0.67972643,  0.81433062],
       [ 1.13593302,  0.06057277,  0.56329694,  0.41290003],
       [-0.94063659, -1.25531842, -0.42635369, -0.12234075],
       [-0.94063659,  0.71851836, -1.29957483, -1.32663251],
       [-0.68106539,  1.37646396, -1.29957483, -1.32663251],
       [ 2.43378902,  1.

In [152]:
scale.transform(test_X)

array([[ 1.65507542, -0.15874243,  1.26187385,  1.2157612 ],
       [-1.9789214 , -0.15874243, -1.5324338 , -1.4604427 ],
       [ 2.43378902, -0.59737283,  1.72759179,  1.08195101],
       [ 0.09764821,  0.27988797,  0.62151168,  0.81433062],
       [ 1.91464662, -0.37805763,  1.49473282,  0.81433062],
       [-1.58956459,  0.06057277, -1.29957483, -1.32663251],
       [-1.32999339,  0.71851836, -1.24136009, -1.32663251],
       [ 0.87636182, -0.59737283,  0.5050822 ,  0.41290003],
       [-1.45977899,  0.27988797, -1.41600431, -1.32663251],
       [ 1.26571862, -0.15874243,  1.02901488,  1.2157612 ],
       [-1.58956459,  0.71851836, -1.35778957, -1.19282231],
       [-0.55127979,  1.81509436, -1.18314534, -1.05901212],
       [-0.55127979,  1.37646396, -1.29957483, -1.32663251],
       [-1.32999339, -0.15874243, -1.35778957, -1.4604427 ],
       [ 0.61679062,  0.49920317,  0.56329694,  0.54671023],
       [ 0.74657622, -0.59737283,  1.08722962,  1.2157612 ],
       [-1.07042219, -2.

In [145]:
joblib.dump(scale, "scaling.pkl")

['scaling.pkl']

In [86]:
train_X.iloc[0,1] = np.NaN
test_X.iloc[0,1] = np.NaN


In [87]:
train_X.isna().sum()

sepal length (cm)    0
sepal width (cm)     1
petal length (cm)    0
petal width (cm)     0
dtype: int64

In [88]:
test_X.isna().sum()

sepal length (cm)    0
sepal width (cm)     1
petal length (cm)    0
petal width (cm)     0
dtype: int64

In [89]:
impute = SimpleImputer(strategy='mean')

In [90]:
impute.fit_transform(train_X)

array([[6.6       , 3.07307692, 4.4       , 1.4       ],
       [6.9       , 3.2       , 5.7       , 2.3       ],
       [4.4       , 2.9       , 1.4       , 0.2       ],
       [6.7       , 3.        , 5.        , 1.7       ],
       [6.        , 2.7       , 5.1       , 1.6       ],
       [4.5       , 2.3       , 1.3       , 0.3       ],
       [4.4       , 3.        , 1.3       , 0.2       ],
       [6.2       , 2.2       , 4.5       , 1.5       ],
       [7.2       , 3.2       , 6.        , 1.8       ],
       [5.8       , 2.7       , 5.1       , 1.9       ],
       [5.7       , 3.        , 4.2       , 1.2       ],
       [6.3       , 2.7       , 4.9       , 1.8       ],
       [6.7       , 3.1       , 4.7       , 1.5       ],
       [5.1       , 2.5       , 3.        , 1.1       ],
       [5.1       , 3.4       , 1.5       , 0.2       ],
       [5.3       , 3.7       , 1.5       , 0.2       ],
       [7.7       , 3.8       , 6.7       , 2.2       ],
       [5.6       , 3.        ,

In [91]:
joblib.dump(impute, 'impute.pkl')

['impute.pkl']

In [70]:
encode  = LabelEncoder()

In [72]:
encode.fit_transform(train_X['flower'])

array([2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 2, 0, 2, 1, 1, 2,
       0, 1, 2, 2, 2, 2, 1, 0, 2, 0, 1, 1, 2, 0, 2, 1, 0, 0, 1, 2, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 2, 1, 2, 0, 2, 0, 2, 0, 2, 2, 0, 0, 1, 2, 0,
       1, 2, 2, 1, 2, 0, 1, 1, 1, 2, 1, 0, 0, 1, 2, 1, 0, 2, 0, 2, 1, 1,
       0, 2, 1, 0, 0, 1, 2, 0, 0, 2, 1, 0, 1, 1, 2, 0, 2])

In [73]:
joblib.dump(encode, 'encode.pkl')

['encode.pkl']

In [97]:
train_X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
75                 6.6               NaN                4.4               1.4
120                6.9               3.2                5.7               2.3
8                  4.4               2.9                1.4               0.2
77                 6.7               3.0                5.0               1.7
83                 6.0               2.7                5.1               1.6
..                 ...               ...                ...               ...
74                 6.4               2.9                4.3               1.3
20                 5.4               3.4                1.7               0.2
9                  4.9               3.1                1.5               0.1
148                6.2               3.4                5.4               2.3
81                 5.5               2.4                3.7               1.0

[105 rows x 4 columns]

In [108]:
pipe = Pipeline([('impute', SimpleImputer(strategy='mean')),
                 ('scale',StandardScaler()), 
                  ('model', RandomForestClassifier())])

In [109]:
pipe.fit(train_X,train_y)

Pipeline(steps=[('impute', SimpleImputer()), ('scale', StandardScaler()),
                ('model', RandomForestClassifier())])

In [110]:
pipe.predict(train_X)

array([1, 2, 0, 1, 1, 0, 0, 1, 2, 2, 1, 2, 1, 1, 0, 0, 2, 1, 2, 2, 2, 1,
       0, 0, 1, 0, 0, 2, 2, 0, 2, 0, 1, 2, 0, 2, 0, 2, 0, 2, 0, 0, 1, 1,
       2, 0, 0, 1, 2, 2, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 2, 1, 1, 2, 1,
       2, 2, 0, 2, 0, 2, 1, 0, 2, 2, 1, 2, 0, 0, 1, 1, 2, 2, 0, 2, 1, 0,
       2, 1, 1, 0, 0, 0, 1, 2, 2, 2, 0, 1, 1, 0, 0, 2, 1])

In [111]:
pipe.predict(test_X)

array([2, 0, 2, 2, 2, 0, 0, 1, 0, 2, 0, 0, 0, 0, 1, 2, 1, 1, 1, 2, 2, 2,
       2, 2, 0, 1, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 0, 0, 2, 1, 2, 0, 1, 1,
       2])

In [112]:
joblib.dump(pipe, 'pipe.pkl')

['pipe.pkl']

In [131]:
pipe = make_pipeline((SimpleImputer(strategy='mean')),
                 (StandardScaler()), 
                  (RandomForestClassifier()))

In [132]:
parameters = [{
    'randomforestclassifier': [RandomForestClassifier()],
    'randomforestclassifier__n_estimators':[25,50,75,100], 
    'randomforestclassifier__max_depth':[1,2,3,4,5,6,7,8,9], 
    'randomforestclassifier__min_samples_leaf':[1,2,3,4,5]}]

In [133]:
gridsearch = GridSearchCV(pipe,parameters,cv = 5, verbose = 1)


In [134]:
gridsearch.fit(train_X,train_y)

Fitting 5 folds for each of 180 candidates, totalling 900 fits


GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('simpleimputer', SimpleImputer()),
                                       ('standardscaler', StandardScaler()),
                                       ('randomforestclassifier',
                                        RandomForestClassifier())]),
             param_grid=[{'randomforestclassifier': [RandomForestClassifier(max_depth=9,
                                                                            min_samples_leaf=4,
                                                                            n_estimators=25)],
                          'randomforestclassifier__max_depth': [1, 2, 3, 4, 5,
                                                                6, 7, 8, 9],
                          'randomforestclassifier__min_samples_leaf': [1, 2, 3,
                                                                       4, 5],
                          'randomforestclassifier__n_estimators': [25, 50, 75,
                     

In [135]:
gridsearch.best_estimator_

Pipeline(steps=[('simpleimputer', SimpleImputer()),
                ('standardscaler', StandardScaler()),
                ('randomforestclassifier',
                 RandomForestClassifier(max_depth=9, min_samples_leaf=4,
                                        n_estimators=25))])

In [136]:
gridsearch.score(test_X, test_y)

0.9777777777777777

In [137]:
joblib.dump(gridsearch,"best_model_pipe.pkl")

['best_model_pipe.pkl']