### Numpy

In [2]:
import numpy as np

In [2]:
array1 = np.array([1, 2, 3, 4, 5])

In [3]:
array1

array([1, 2, 3, 4, 5])

In [4]:
type(array1)

numpy.ndarray

In [5]:
array1.shape

(5,)

In [6]:
array1.ndim

1

In [7]:
array2 = np.array([[1, 2, 3, 4, 5], [11, 22, 33, 44, 55]])

In [8]:
array2.shape

(2, 5)

In [10]:
array2.ndim

2

In [12]:
array1 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
array1
print(type(array1))
print(array1.shape)
print(array1.ndim)


<class 'numpy.ndarray'>
(2, 5)
2


In [24]:
array2 = np.array([[1,2,3],[11,22,np.nan]], dtype = float)


In [25]:
array2

array([[ 1.,  2.,  3.],
       [11., 22., nan]])

In [18]:
array2.shape

(2, 3)

In [21]:
array_reshape = array2.reshape(3,2)

In [22]:
array_reshape

array([[ 1.,  2.],
       [ 3., 11.],
       [22., 33.]])

In [23]:
array_reshape.shape

(3, 2)

In [27]:
array2 = np.array([[[[1,2,3,4,5],[4,5,6,7,8],[1.2,3.4,5.6,7.8,9.1],[4,4,4,4,5]]]])


In [33]:
array2 = np.array([[1,2,3,4,5],[4,5,6,7,8],[1.2,3.4,5.6,7.8,9.1],[4,4,4,4,5]])

In [34]:
array2.shape

(4, 5)

In [32]:
array2

array([[[[1. , 2. , 3. , 4. , 5. ],
         [4. , 5. , 6. , 7. , 8. ],
         [1.2, 3.4, 5.6, 7.8, 9.1],
         [4. , 4. , 4. , 4. , 5. ]]]])

In [31]:
np.shape?

In [28]:
array2.shape

(1, 1, 4, 5)

In [29]:
array2.ndim

4

In [30]:
array2.shape?

In [35]:
array6 = np.array([[1,2,3.3],[4,5,6]])


TypeError: Field elements must be 2- or 3-tuples, got '4'

In [45]:
array2 = np.array([[1,2,3,4,5],[4,5,6,7,8],[1.2,3.4,5.6,7.8,9.1],[4,4,4,4,5]], dtype = int)


In [36]:
array_Zero = np.zeros(8)

In [37]:
array_Zero

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [40]:
array_ones = np.ones([3, 3], dtype=int)

In [41]:
array_ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### Creating an array with existing data

In [42]:
x1 = ([3, 5], [5, 4], [6, 7])
a1 = np.asarray(x1, dtype=float)

In [46]:
np.array(x1)

array([[3, 5],
       [5, 4],
       [6, 7]])

In [44]:
type(x1)

tuple

In [43]:
a1

array([[3., 5.],
       [5., 4.],
       [6., 7.]])

### Array from numerical ranges


In [47]:
a1 = np.arange(0, 20, 3)

In [48]:
a1

array([ 0,  3,  6,  9, 12, 15, 18])

In [53]:
a1 = np.linspace(10, 20, 3)

In [54]:
a1

array([10., 15., 20.])

## Slicing

In [60]:
list1 = np.arange(10)
array1 = slice(2, 9, 3)
list1[array1]

array([2, 5, 8])

In [58]:
list1 = np.arange(10)
array1 = slice(2, 9)
list1[array1]

array([2, 3, 4, 5, 6, 7, 8])

In [57]:
list1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
list1 = np.arange(10)
array1 = list1[2: 9]
list1[array1]

array([2, 3, 4, 5, 6, 7, 8])

In [62]:
list1 = np.arange(10)
array1 = list1[2: 9: 2]
list1[array1]

array([2, 4, 6, 8])

In [63]:
len(list1)

10

In [65]:
array1

array([2, 4, 6, 8])

In [64]:
array1.shape

(4,)

In [67]:
array1.ndim

1

In [72]:
array7 = np.array([[[1,2,3,4,5],[4,5,6,7,8]],[[1,3,5,7,9],[4,4,4,4,5]]])
print(len(array7))
print(array7.ndim)

2
3


In [71]:
array7

array([[[1, 2, 3, 4, 5],
        [4, 5, 6, 7, 8]],

       [[1, 3, 5, 7, 9],
        [4, 4, 4, 4, 5]]])

In [82]:
array7= np.array([[[1,3,4,5],[3,4,5,6]],[[5,4,5,6],[3,4,5,6]]])


In [83]:
array7.shape

(2, 2, 4)

In [84]:
array7.ndim

3

In [85]:
array7= np.array([[[1,3,4,5],[3,4,5,6],[3,4,5,6]],[[5,4,5,6],[3,4,5,6],[3,4,5,6]],[[5,4,5,6],[3,4,5,6],[3,4,5,6]],[[5,4,5,6],[3,4,5,6],[3,4,5,6]]])


In [86]:
print(array7.shape)
print(array7.ndim)

(4, 3, 4)
3


In [87]:
print(array7)

[[[1 3 4 5]
  [3 4 5 6]
  [3 4 5 6]]

 [[5 4 5 6]
  [3 4 5 6]
  [3 4 5 6]]

 [[5 4 5 6]
  [3 4 5 6]
  [3 4 5 6]]

 [[5 4 5 6]
  [3 4 5 6]
  [3 4 5 6]]]


### Integer indexing

In [88]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = a[[0, 1, 2], [0, 1, 0]]

In [90]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [89]:
print(b)

[1 4 5]


In [91]:
b = a[[0], [0]]

In [92]:
b

array([1])

In [140]:
a1 = np.array([[1,2,3, 5, np.nan, 9],[4, 5,6, 1,2,3],[7,8, 9, 5,6, 1],[10,np.nan,12, 9, 5,6]])
z = a1[1:4, 1:3]
z


array([[ 5.,  6.],
       [ 8.,  9.],
       [nan, 12.]])

In [95]:
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [94]:
z = a1[1:, 1:]
z

array([[ 6,  7,  8],
       [10, 11, 12]])

In [101]:
a1

array([[ 1,  2,  3,  5,  8,  9],
       [ 4,  5,  6,  1,  2,  3],
       [ 7,  8,  9,  5,  6,  1],
       [10, 11, 12,  9,  5,  6]])

In [104]:
a1.shape

(4, 6)

In [103]:
z = a1[:4, :3]
z

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [108]:
a1

array([[ 1,  2,  3,  5,  8,  9],
       [ 4,  5,  6,  1,  2,  3],
       [ 7,  8,  9,  5,  6,  1],
       [10, 11, 12,  9,  5,  6]])

In [110]:
y = a1[1:4, [1, 2, 3]]
y

array([[ 5,  6,  1],
       [ 8,  9,  5],
       [11, 12,  9]])

In [112]:
a1[[1, 2, 3], [1, 2, 3]]

array([5, 9, 9])

In [114]:
a1[1:3, 1:4]

array([[5, 6, 1],
       [8, 9, 5]])

In [122]:
a1

array([[ 1,  2,  3,  5,  8,  9],
       [ 4,  5,  6,  1,  2,  3],
       [ 7,  8,  9,  5,  6,  1],
       [10, 11, 12,  9,  5,  6]])

In [125]:
a1[a1<4]

array([1, 2, 3, 1, 2, 3, 1])

In [120]:
arr1 = np.array([[ 8,  9,  6,  7,  8,  9,  6, 10, 11, 12,  9,  6], [ 8,  9,  6,  7,  8,  9,  6, 10, 11, 12,  9,  6]])

In [121]:
arr1.shape

(2, 12)

In [139]:
a = np.array([1, 5,  8, np.nan, 52, 65, np.nan])
a

array([ 1.,  5.,  8., nan, 52., 65., nan])

In [138]:
a[np.isnan(a)]

array([nan, nan])

In [135]:
a[~np.isnan(a)]

array([ 1.,  5.,  8., 52., 65.])

In [142]:
a1[np.isnan(a1)]

array([nan, nan])

In [131]:
a= np.array([[1,2,'dd'],[5,6,7],[1,2,3],[5,6,7]])
b= a[1:4,1:3]


In [143]:
b

array([['6', '7'],
       ['2', '3'],
       ['6', '7']], dtype='<U11')

In [144]:
b.dtype

dtype('<U11')

In [133]:
a

array([['1', '2', 'dd'],
       ['5', '6', '7'],
       ['1', '2', '3'],
       ['5', '6', '7']], dtype='<U11')

In [145]:
a= np.array([[1,2,1],[5,6,7],[1,2,3],[5,6,7]])
b= np.array([[1,2,1],[5,6,7],[1,2,3],[5,6,7]])


In [146]:
a

array([[1, 2, 1],
       [5, 6, 7],
       [1, 2, 3],
       [5, 6, 7]])

In [147]:
b

array([[1, 2, 1],
       [5, 6, 7],
       [1, 2, 3],
       [5, 6, 7]])

In [148]:
a+b

array([[ 2,  4,  2],
       [10, 12, 14],
       [ 2,  4,  6],
       [10, 12, 14]])

## Broadcasting

In [3]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = x * y


In [4]:
z

array([ 4, 10, 18])

In [5]:
x = np.array([1,2,3])
y = 5
z = x * y

In [6]:
z

array([ 5, 10, 15])

In [ ]:
x= np.array([[1,2,3],[4,5,6]])
y=np.array([[4,5,6],[7,8,9]])
z=x*y
z


In [15]:
x=np.array([[1,2],[4,5], [8, 9]])
y=10
x*y


array([[10, 20],
       [40, 50],
       [80, 90]])

In [ ]:
x2=np.array(6).reshape(2,3)

In [16]:
x

array([[1, 2],
       [4, 5],
       [8, 9]])

In [17]:
x.reshape(2, 3)

array([[1, 2, 4],
       [5, 8, 9]])

In [18]:
arr1 = np.arange(6)
arr1

array([0, 1, 2, 3, 4, 5])

In [21]:
arr1.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([4,5,6])
z = x * y
z


array([[ 4, 10, 18],
       [16, 25, 36],
       [28, 40, 54]])

In [23]:
z.T

array([[ 4, 16, 28],
       [10, 25, 40],
       [18, 36, 54]])

In [24]:
array1 = np.arange(8).reshape(4, 2)
array1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [25]:
array1.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [27]:
b8 = np.array([[1,2,3],[4,5,6]])
b9 = np.array([[3,2,1],[6,5,4]])
z = np.concatenate((b8,b9))
z


array([[1, 2, 3],
       [4, 5, 6],
       [3, 2, 1],
       [6, 5, 4]])

In [ ]:
np.stack((a, b))

In [32]:
x1 = 4
y1 = 5

In [34]:
np.stack((x1, y1))

array([4, 5])

In [35]:
x = np.array([[1,2,3],[3,4,5]])
y = np.array([[11,12,13],[13,14,15]])

np.stack(x)


array([[1, 2, 3],
       [3, 4, 5]])

In [36]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
z = np.stack((a, b))


In [37]:
a

array([1, 2, 3])

In [38]:
b

array([2, 3, 4])

In [39]:
np.stack([a, b],)

array([[1, 2, 3],
       [2, 3, 4]])

In [40]:
np.stack?

In [45]:
arrays = [np.random.randn(2, 2) for _ in range(2)]

In [46]:
arrays

[array([[ 0.25541675, -0.32504463],
        [ 1.51396588,  0.9248838 ]]),
 array([[ 0.68383813,  0.94880493],
        [-0.61223128,  0.34557084]])]

In [49]:
np.stack(arrays, axis=0)

array([[[ 0.25541675, -0.32504463],
        [ 1.51396588,  0.9248838 ]],

       [[ 0.68383813,  0.94880493],
        [-0.61223128,  0.34557084]]])

In [ ]:
np.stack((a, b), axis=1)

In [52]:
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [53]:
y

array([[10, 20],
       [30, 40],
       [50, 60]])

In [50]:
x = np.array([[1,2],[3,4],[5,6]])  
y = np.array([[10,20],[30,40],[50,60]])
np.stack((x,y), axis=0)


array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[10, 20],
        [30, 40],
        [50, 60]]])

In [51]:
np.stack((x,y), axis=1)

array([[[ 1,  2],
        [10, 20]],

       [[ 3,  4],
        [30, 40]],

       [[ 5,  6],
        [50, 60]]])

In [54]:
np.vstack((x, y))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [10, 20],
       [30, 40],
       [50, 60]])

In [55]:
np.hstack((x, y))

array([[ 1,  2, 10, 20],
       [ 3,  4, 30, 40],
       [ 5,  6, 50, 60]])

In [59]:
a = np.arange(9)
np.split(a, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [57]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [60]:
arr1 = np.array([[20, 30, 40], [50, 80, 30]])

In [61]:
arr1

array([[20, 30, 40],
       [50, 80, 30]])

In [66]:
np.append(arr1, [[10, 20, 30], [60, 40, 20]], axis=1)

array([[20, 30, 40, 10, 20, 30],
       [50, 80, 30, 60, 40, 20]])

In [67]:
np.append(arr1, [[10, 20, 30], [60, 40, 20]], axis=0)

array([[20, 30, 40],
       [50, 80, 30],
       [10, 20, 30],
       [60, 40, 20]])

In [82]:
x = ([[10,20,30],[40,50,60]])
x

[[10, 20, 30], [40, 50, 60]]

In [86]:
np.insert(x, 4, [5])

array([10, 20, 30, 40,  5, 50, 60])

In [73]:
np.delete?

In [87]:
x

[[10, 20, 30], [40, 50, 60]]

In [88]:
uniq = np.array([1,2,43,4,5,6,7,7,8,8])
np.unique(uniq)


array([ 1,  2,  4,  5,  6,  7,  8, 43])

In [89]:
np.add?

In [ ]:
np.subtract?

In [ ]:
np.multiply?

In [ ]:
np.divide?

In [90]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[5,6,7],[6,4,9]])

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))


[[ 6  8 10]
 [10  9 15]]
[[-4 -4 -4]
 [-2  1 -3]]
[[ 5 12 21]
 [24 20 54]]
[[0.2        0.33333333 0.42857143]
 [0.66666667 1.25       0.66666667]]


In [92]:
array1 = np.array([3, 5, 6])
np.power(array1, 3)

array([ 27, 125, 216], dtype=int32)

In [95]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.percentile(array1, 80, axis=1)

array([2.6, 5.6, 8.6])

In [96]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
np.mean?

In [ ]:
np.median

In [ ]:
np.std

In [100]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(np.mean(x,axis=0))
print(np.median(x,axis=0))
print(np.std(x,axis=0))


[4. 5. 6.]
[4. 5. 6.]
[2.44948974 2.44948974 2.44948974]


## Pandas

In [101]:
import pandas as pd

In [103]:
a = np.array([10, 2, 50, 70])
s = pd.Series(a)

In [102]:
type(a)

numpy.ndarray

In [104]:
print(s)

0    10
1     2
2    50
3    70
dtype: int32


In [105]:
type(s)

pandas.core.series.Series

In [106]:
a = np.array([10, 2, 50, 70])
s = pd.Series(a, index=[10, 20, 30, 40])

In [108]:
len(a)

4

In [116]:
list(range(10, 14))

[10, 11, 12, 13]

In [107]:
s

10    10
20     2
30    50
40    70
dtype: int32

In [117]:
dict1 = {1: 'value1',2: 'value 2',3: 'value 3'}
s = pd.Series(dict1)


In [119]:
s[2]

'value 2'

In [ ]:
pd.Series([], index=[])

In [124]:
dict1= {'First' : 10, 'Second' : 2, 'Third' : 50}
s1 = pd.Series(dict1)
s2 = pd.Series(dict1, index = ['Second','Third','First'])


In [125]:
s1

First     10
Second     2
Third     50
dtype: int64

In [126]:
s2

Second     2
Third     50
First     10
dtype: int64

In [129]:
s1[1:]

Second     2
Third     50
dtype: int64