### Numpy

In [2]:
import numpy as np

In [2]:
array1 = np.array([1, 2, 3, 4, 5])

In [3]:
array1

array([1, 2, 3, 4, 5])

In [4]:
type(array1)

numpy.ndarray

In [5]:
array1.shape

(5,)

In [6]:
array1.ndim

1

In [7]:
array2 = np.array([[1, 2, 3, 4, 5], [11, 22, 33, 44, 55]])

In [8]:
array2.shape

(2, 5)

In [10]:
array2.ndim

2

In [12]:
array1 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
array1
print(type(array1))
print(array1.shape)
print(array1.ndim)


<class 'numpy.ndarray'>
(2, 5)
2


In [24]:
array2 = np.array([[1,2,3],[11,22,np.nan]], dtype = float)


In [25]:
array2

array([[ 1.,  2.,  3.],
       [11., 22., nan]])

In [18]:
array2.shape

(2, 3)

In [21]:
array_reshape = array2.reshape(3,2)

In [22]:
array_reshape

array([[ 1.,  2.],
       [ 3., 11.],
       [22., 33.]])

In [23]:
array_reshape.shape

(3, 2)

In [27]:
array2 = np.array([[[[1,2,3,4,5],[4,5,6,7,8],[1.2,3.4,5.6,7.8,9.1],[4,4,4,4,5]]]])


In [33]:
array2 = np.array([[1,2,3,4,5],[4,5,6,7,8],[1.2,3.4,5.6,7.8,9.1],[4,4,4,4,5]])

In [34]:
array2.shape

(4, 5)

In [32]:
array2

array([[[[1. , 2. , 3. , 4. , 5. ],
         [4. , 5. , 6. , 7. , 8. ],
         [1.2, 3.4, 5.6, 7.8, 9.1],
         [4. , 4. , 4. , 4. , 5. ]]]])

In [31]:
np.shape?

In [28]:
array2.shape

(1, 1, 4, 5)

In [29]:
array2.ndim

4

In [30]:
array2.shape?

In [35]:
array6 = np.array([[1,2,3.3],[4,5,6]])


TypeError: Field elements must be 2- or 3-tuples, got '4'

In [45]:
array2 = np.array([[1,2,3,4,5],[4,5,6,7,8],[1.2,3.4,5.6,7.8,9.1],[4,4,4,4,5]], dtype = int)


In [36]:
array_Zero = np.zeros(8)

In [37]:
array_Zero

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [40]:
array_ones = np.ones([3, 3], dtype=int)

In [41]:
array_ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### Creating an array with existing data

In [42]:
x1 = ([3, 5], [5, 4], [6, 7])
a1 = np.asarray(x1, dtype=float)

In [46]:
np.array(x1)

array([[3, 5],
       [5, 4],
       [6, 7]])

In [44]:
type(x1)

tuple

In [43]:
a1

array([[3., 5.],
       [5., 4.],
       [6., 7.]])

### Array from numerical ranges


In [47]:
a1 = np.arange(0, 20, 3)

In [48]:
a1

array([ 0,  3,  6,  9, 12, 15, 18])

In [53]:
a1 = np.linspace(10, 20, 3)

In [54]:
a1

array([10., 15., 20.])

## Slicing

In [60]:
list1 = np.arange(10)
array1 = slice(2, 9, 3)
list1[array1]

array([2, 5, 8])

In [58]:
list1 = np.arange(10)
array1 = slice(2, 9)
list1[array1]

array([2, 3, 4, 5, 6, 7, 8])

In [57]:
list1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
list1 = np.arange(10)
array1 = list1[2: 9]
list1[array1]

array([2, 3, 4, 5, 6, 7, 8])

In [62]:
list1 = np.arange(10)
array1 = list1[2: 9: 2]
list1[array1]

array([2, 4, 6, 8])

In [63]:
len(list1)

10

In [65]:
array1

array([2, 4, 6, 8])

In [64]:
array1.shape

(4,)

In [67]:
array1.ndim

1

In [72]:
array7 = np.array([[[1,2,3,4,5],[4,5,6,7,8]],[[1,3,5,7,9],[4,4,4,4,5]]])
print(len(array7))
print(array7.ndim)

2
3


In [71]:
array7

array([[[1, 2, 3, 4, 5],
        [4, 5, 6, 7, 8]],

       [[1, 3, 5, 7, 9],
        [4, 4, 4, 4, 5]]])

In [82]:
array7= np.array([[[1,3,4,5],[3,4,5,6]],[[5,4,5,6],[3,4,5,6]]])


In [83]:
array7.shape

(2, 2, 4)

In [84]:
array7.ndim

3

In [85]:
array7= np.array([[[1,3,4,5],[3,4,5,6],[3,4,5,6]],[[5,4,5,6],[3,4,5,6],[3,4,5,6]],[[5,4,5,6],[3,4,5,6],[3,4,5,6]],[[5,4,5,6],[3,4,5,6],[3,4,5,6]]])


In [86]:
print(array7.shape)
print(array7.ndim)

(4, 3, 4)
3


In [87]:
print(array7)

[[[1 3 4 5]
  [3 4 5 6]
  [3 4 5 6]]

 [[5 4 5 6]
  [3 4 5 6]
  [3 4 5 6]]

 [[5 4 5 6]
  [3 4 5 6]
  [3 4 5 6]]

 [[5 4 5 6]
  [3 4 5 6]
  [3 4 5 6]]]


### Integer indexing

In [88]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = a[[0, 1, 2], [0, 1, 0]]

In [90]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [89]:
print(b)

[1 4 5]


In [91]:
b = a[[0], [0]]

In [92]:
b

array([1])

In [140]:
a1 = np.array([[1,2,3, 5, np.nan, 9],[4, 5,6, 1,2,3],[7,8, 9, 5,6, 1],[10,np.nan,12, 9, 5,6]])
z = a1[1:4, 1:3]
z


array([[ 5.,  6.],
       [ 8.,  9.],
       [nan, 12.]])

In [95]:
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [94]:
z = a1[1:, 1:]
z

array([[ 6,  7,  8],
       [10, 11, 12]])

In [101]:
a1

array([[ 1,  2,  3,  5,  8,  9],
       [ 4,  5,  6,  1,  2,  3],
       [ 7,  8,  9,  5,  6,  1],
       [10, 11, 12,  9,  5,  6]])

In [104]:
a1.shape

(4, 6)

In [103]:
z = a1[:4, :3]
z

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [108]:
a1

array([[ 1,  2,  3,  5,  8,  9],
       [ 4,  5,  6,  1,  2,  3],
       [ 7,  8,  9,  5,  6,  1],
       [10, 11, 12,  9,  5,  6]])

In [110]:
y = a1[1:4, [1, 2, 3]]
y

array([[ 5,  6,  1],
       [ 8,  9,  5],
       [11, 12,  9]])

In [112]:
a1[[1, 2, 3], [1, 2, 3]]

array([5, 9, 9])

In [114]:
a1[1:3, 1:4]

array([[5, 6, 1],
       [8, 9, 5]])

In [122]:
a1

array([[ 1,  2,  3,  5,  8,  9],
       [ 4,  5,  6,  1,  2,  3],
       [ 7,  8,  9,  5,  6,  1],
       [10, 11, 12,  9,  5,  6]])

In [125]:
a1[a1<4]

array([1, 2, 3, 1, 2, 3, 1])

In [120]:
arr1 = np.array([[ 8,  9,  6,  7,  8,  9,  6, 10, 11, 12,  9,  6], [ 8,  9,  6,  7,  8,  9,  6, 10, 11, 12,  9,  6]])

In [121]:
arr1.shape

(2, 12)

In [139]:
a = np.array([1, 5,  8, np.nan, 52, 65, np.nan])
a

array([ 1.,  5.,  8., nan, 52., 65., nan])

In [138]:
a[np.isnan(a)]

array([nan, nan])

In [135]:
a[~np.isnan(a)]

array([ 1.,  5.,  8., 52., 65.])

In [142]:
a1[np.isnan(a1)]

array([nan, nan])

In [131]:
a= np.array([[1,2,'dd'],[5,6,7],[1,2,3],[5,6,7]])
b= a[1:4,1:3]


In [143]:
b

array([['6', '7'],
       ['2', '3'],
       ['6', '7']], dtype='<U11')

In [144]:
b.dtype

dtype('<U11')

In [133]:
a

array([['1', '2', 'dd'],
       ['5', '6', '7'],
       ['1', '2', '3'],
       ['5', '6', '7']], dtype='<U11')

In [145]:
a= np.array([[1,2,1],[5,6,7],[1,2,3],[5,6,7]])
b= np.array([[1,2,1],[5,6,7],[1,2,3],[5,6,7]])


In [146]:
a

array([[1, 2, 1],
       [5, 6, 7],
       [1, 2, 3],
       [5, 6, 7]])

In [147]:
b

array([[1, 2, 1],
       [5, 6, 7],
       [1, 2, 3],
       [5, 6, 7]])

In [148]:
a+b

array([[ 2,  4,  2],
       [10, 12, 14],
       [ 2,  4,  6],
       [10, 12, 14]])

## Broadcasting

In [3]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = x * y


In [4]:
z

array([ 4, 10, 18])

In [5]:
x = np.array([1,2,3])
y = 5
z = x * y

In [6]:
z

array([ 5, 10, 15])

In [ ]:
x= np.array([[1,2,3],[4,5,6]])
y=np.array([[4,5,6],[7,8,9]])
z=x*y
z


In [15]:
x=np.array([[1,2],[4,5], [8, 9]])
y=10
x*y


array([[10, 20],
       [40, 50],
       [80, 90]])

In [ ]:
x2=np.array(6).reshape(2,3)

In [16]:
x

array([[1, 2],
       [4, 5],
       [8, 9]])

In [17]:
x.reshape(2, 3)

array([[1, 2, 4],
       [5, 8, 9]])

In [18]:
arr1 = np.arange(6)
arr1

array([0, 1, 2, 3, 4, 5])

In [21]:
arr1.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([4,5,6])
z = x * y
z


array([[ 4, 10, 18],
       [16, 25, 36],
       [28, 40, 54]])

In [23]:
z.T

array([[ 4, 16, 28],
       [10, 25, 40],
       [18, 36, 54]])

In [24]:
array1 = np.arange(8).reshape(4, 2)
array1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [25]:
array1.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [27]:
b8 = np.array([[1,2,3],[4,5,6]])
b9 = np.array([[3,2,1],[6,5,4]])
z = np.concatenate((b8,b9))
z


array([[1, 2, 3],
       [4, 5, 6],
       [3, 2, 1],
       [6, 5, 4]])

In [ ]:
np.stack((a, b))

In [32]:
x1 = 4
y1 = 5

In [34]:
np.stack((x1, y1))

array([4, 5])

In [35]:
x = np.array([[1,2,3],[3,4,5]])
y = np.array([[11,12,13],[13,14,15]])

np.stack(x)


array([[1, 2, 3],
       [3, 4, 5]])

In [36]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
z = np.stack((a, b))


In [37]:
a

array([1, 2, 3])

In [38]:
b

array([2, 3, 4])

In [39]:
np.stack([a, b],)

array([[1, 2, 3],
       [2, 3, 4]])

In [40]:
np.stack?

In [45]:
arrays = [np.random.randn(2, 2) for _ in range(2)]

In [46]:
arrays

[array([[ 0.25541675, -0.32504463],
        [ 1.51396588,  0.9248838 ]]),
 array([[ 0.68383813,  0.94880493],
        [-0.61223128,  0.34557084]])]

In [49]:
np.stack(arrays, axis=0)

array([[[ 0.25541675, -0.32504463],
        [ 1.51396588,  0.9248838 ]],

       [[ 0.68383813,  0.94880493],
        [-0.61223128,  0.34557084]]])

In [ ]:
np.stack((a, b), axis=1)

In [52]:
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [53]:
y

array([[10, 20],
       [30, 40],
       [50, 60]])

In [50]:
x = np.array([[1,2],[3,4],[5,6]])  
y = np.array([[10,20],[30,40],[50,60]])
np.stack((x,y), axis=0)


array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[10, 20],
        [30, 40],
        [50, 60]]])

In [51]:
np.stack((x,y), axis=1)

array([[[ 1,  2],
        [10, 20]],

       [[ 3,  4],
        [30, 40]],

       [[ 5,  6],
        [50, 60]]])

In [54]:
np.vstack((x, y))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [10, 20],
       [30, 40],
       [50, 60]])

In [55]:
np.hstack((x, y))

array([[ 1,  2, 10, 20],
       [ 3,  4, 30, 40],
       [ 5,  6, 50, 60]])

In [59]:
a = np.arange(9)
np.split(a, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [57]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [60]:
arr1 = np.array([[20, 30, 40], [50, 80, 30]])

In [61]:
arr1

array([[20, 30, 40],
       [50, 80, 30]])

In [66]:
np.append(arr1, [[10, 20, 30], [60, 40, 20]], axis=1)

array([[20, 30, 40, 10, 20, 30],
       [50, 80, 30, 60, 40, 20]])

In [67]:
np.append(arr1, [[10, 20, 30], [60, 40, 20]], axis=0)

array([[20, 30, 40],
       [50, 80, 30],
       [10, 20, 30],
       [60, 40, 20]])

In [82]:
x = ([[10,20,30],[40,50,60]])
x

[[10, 20, 30], [40, 50, 60]]

In [86]:
np.insert(x, 4, [5])

array([10, 20, 30, 40,  5, 50, 60])

In [73]:
np.delete?

In [87]:
x

[[10, 20, 30], [40, 50, 60]]

In [88]:
uniq = np.array([1,2,43,4,5,6,7,7,8,8])
np.unique(uniq)


array([ 1,  2,  4,  5,  6,  7,  8, 43])

In [89]:
np.add?

In [ ]:
np.subtract?

In [ ]:
np.multiply?

In [ ]:
np.divide?

In [90]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[5,6,7],[6,4,9]])

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))


[[ 6  8 10]
 [10  9 15]]
[[-4 -4 -4]
 [-2  1 -3]]
[[ 5 12 21]
 [24 20 54]]
[[0.2        0.33333333 0.42857143]
 [0.66666667 1.25       0.66666667]]


In [92]:
array1 = np.array([3, 5, 6])
np.power(array1, 3)

array([ 27, 125, 216], dtype=int32)

In [95]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.percentile(array1, 80, axis=1)

array([2.6, 5.6, 8.6])

In [96]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
np.mean?

In [ ]:
np.median

In [ ]:
np.std

In [100]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(np.mean(x,axis=0))
print(np.median(x,axis=0))
print(np.std(x,axis=0))


[4. 5. 6.]
[4. 5. 6.]
[2.44948974 2.44948974 2.44948974]


## Pandas

In [2]:
import pandas as pd
import numpy as np

In [103]:
a = np.array([10, 2, 50, 70])
s = pd.Series(a)

In [102]:
type(a)

numpy.ndarray

In [104]:
print(s)

0    10
1     2
2    50
3    70
dtype: int32


In [105]:
type(s)

pandas.core.series.Series

In [106]:
a = np.array([10, 2, 50, 70])
s = pd.Series(a, index=[10, 20, 30, 40])

In [108]:
len(a)

4

In [116]:
list(range(10, 14))

[10, 11, 12, 13]

In [107]:
s

10    10
20     2
30    50
40    70
dtype: int32

In [117]:
dict1 = {1: 'value1',2: 'value 2',3: 'value 3'}
s = pd.Series(dict1)


In [119]:
s[2]

'value 2'

In [ ]:
pd.Series([], index=[])

In [124]:
dict1= {'First' : 10, 'Second' : 2, 'Third' : 50}
s1 = pd.Series(dict1)
s2 = pd.Series(dict1, index = ['Second','Third','First'])


In [125]:
s1

First     10
Second     2
Third     50
dtype: int64

In [126]:
s2

Second     2
Third     50
First     10
dtype: int64

In [129]:
s1[1:]

Second     2
Third     50
dtype: int64

### Creating a dataframe


In [3]:
df = pd.DataFrame()

In [4]:
print(df)

Empty DataFrame
Columns: []
Index: []


## creating df with a list

In [7]:
l1 = list(range(5))
df = pd.DataFrame(l1)
df


0
0  0
1  1
2  2
3  3
4  4

In [10]:
list2 = [['raj',1, 10],['raj1',2, 56], ['Name3', 3, 66]]
df = pd.DataFrame(list2, columns=['Name','Slno', 'Column3'])
df



Name  Slno  Column3
0    raj     1       10
1   raj1     2       56
2  Name3     3       66

In [13]:
list2 = [[3,33],[4,44],[5,55]]
df = pd.DataFrame(list2, columns = ['Col1', 'Col2'])


In [14]:
df

Col1  Col2
0     3    33
1     4    44
2     5    55

In [19]:
list2=[['Raj',1,10], ['Nath',2,10]]
df=pd.DataFrame(list2,columns=['Name','SNo','Col1'])
df


Name  SNo  Col1
0   Raj    1    10
1  Nath    2    10

In [20]:
list2 = [[2, 3], [4, 5], [6, 7], [9, 10]]
df = pd.DataFrame(list2, columns= ['first', 'second'])
print(df)


   first  second
0      2       3
1      4       5
2      6       7
3      9      10


In [22]:
d1 = {'cks':[1,2,3],'rcb':[4,5,6],'MI':[7,8,9]}
dataf2 = pd.DataFrame(d1, index=[1, 2, 3])
dataf2


cks  rcb  MI
1    1    4   7
2    2    5   8
3    3    6   9

In [26]:
list_col = ['cks', 'MI']

In [27]:
dataf2[list_col]

cks  MI
1    1   7
2    2   8
3    3   9

In [28]:
dataf2[['cks', 'MI']]

cks  MI
1    1   7
2    2   8
3    3   9

In [30]:
dict1 = {'state': ['Tamilnadu','telangana','karanataka'], 'city': ['Chennai','Hyderabad','Banglore']}

# list_col = df4[['state','city']]



In [31]:
pd.DataFrame(dict1)

state       city
0   Tamilnadu    Chennai
1   telangana  Hyderabad
2  karanataka   Banglore

In [ ]:
print(list_col)
df4[list_col]

In [38]:
Dict1= {'50': [1000,2000,300],'30': [10000,40000,50000]}
df1=pd.DataFrame(Dict1, index=[1,2,3])
df1


50     30
1  1000  10000
2  2000  40000
3   300  50000

In [49]:
df1 = df1.rename(columns={'50':'CSK', '30':'MI'})
df1

CSK     MI
1  1000  10000
2  2000  40000
3   300  50000

In [43]:
dict1 = {'state': ['Tamilnadu','telangana','karanataka'], 'city': ['Chennai','Hyderabad','Banglore'], 'const': [10,20,30]}
df4 = pd.DataFrame(dict1)
df4



state       city  const
0   Tamilnadu    Chennai     10
1   telangana  Hyderabad     20
2  karanataka   Banglore     30

In [44]:
type(df4)

pandas.core.frame.DataFrame

In [45]:

list_col = df4[['state','city']] #select only these columns in my df4


In [46]:
list_col

state       city
0   Tamilnadu    Chennai
1   telangana  Hyderabad
2  karanataka   Banglore

In [47]:
type(list_col)

pandas.core.frame.DataFrame

In [54]:
df4

state       city  const
0   Tamilnadu    Chennai     10
1   telangana  Hyderabad     20
2  karanataka   Banglore     30

In [59]:
df4[0:2]['state']

0    Tamilnadu
1    telangana
Name: state, dtype: object

In [67]:
df4

state       city  const
0   Tamilnadu    Chennai     10
1   telangana  Hyderabad     20
2  karanataka   Banglore     30

In [71]:
dict2 = {'state': ['Tamilnadu','telangana','karanataka','goa'], 
         'city': ['Chennai','Hyderabad','Banglore','panaji'], 
         'const': [10,20,30,40], 
         'No_of_school': [100,200,300,105]}

df = pd.DataFrame(dict2)


In [72]:
df

state       city  const  No_of_school
0   Tamilnadu    Chennai     10           100
1   telangana  Hyderabad     20           200
2  karanataka   Banglore     30           300
3         goa     panaji     40           105

In [73]:
df['No_of_hosp'] = pd.Series([5,13,12,4])
df

state       city  const  No_of_school  No_of_hosp
0   Tamilnadu    Chennai     10           100           5
1   telangana  Hyderabad     20           200          13
2  karanataka   Banglore     30           300          12
3         goa     panaji     40           105           4

In [75]:
dict1 = {'Age':[10,20,30,40],
        'Gender':[0,1,0,1]}
df =pd.DataFrame(dict1,index=[1,2,3,4])
#df.rename(columns={"Age":"MyAge","Gender":"Gender"})
df


Age  Gender
1   10       0
2   20       1
3   30       0
4   40       1

In [76]:
val = df['Age'].values[0:3]
val = pd.DataFrame(val,columns=['Age'])
val


Age
0   10
1   20
2   30

In [77]:
df['Age'].values[0:3]

array([10, 20, 30], dtype=int64)

In [104]:
dict2={'Name':['madhu','geetha','tamil','vino'],'total':[90,80,70,60],'marks':[10,20,30,40]}
s=pd.DataFrame(dict2,index=[11,12,13,14])
# s['school']=pd.Series(['kv','john','donbosco','kvig'])


In [105]:
s['school'] = pd.Series(['kv','john','donbosco','kvig'], index=[11,12,13,14])

In [106]:
s

Name  total  marks    school
11   madhu     90     10        kv
12  geetha     80     20      john
13   tamil     70     30  donbosco
14    vino     60     40      kvig

In [84]:
s['Add'] = s['total'] + s['marks']

In [85]:
s

Name  total  marks    school  Add
11   madhu     90     10        kv  100
12  geetha     80     20      john  100
13   tamil     70     30  donbosco  100
14    vino     60     40      kvig  100

In [86]:
del s['Add']

In [87]:
s

Name  total  marks    school
11   madhu     90     10        kv
12  geetha     80     20      john
13   tamil     70     30  donbosco
14    vino     60     40      kvig

In [88]:
s.drop('total', axis=1, inplace=True)

In [95]:
s

Name  total  marks    school
11   madhu     90     10        kv
12  geetha     80     20      john
13   tamil     70     30  donbosco
14    vino     60     40      kvig

In [97]:
s = s.drop(['Name', 'marks'], axis=1)

In [114]:
s

Name  total  marks    school
11   madhu     90     10        kv
12  geetha     80     20      john
13   tamil     70     30  donbosco
14    vino     60     40      kvig

In [116]:
s.drop([11,12], axis=0, inplace=True)
s

Name  total  marks    school
13  tamil     70     30  donbosco
14   vino     60     40      kvig

In [108]:
s

Name  total  marks    school
11   madhu     90     10        kv
12  geetha     80     20      john
13   tamil     70     30  donbosco
14    vino     60     40      kvig

In [120]:
dict2 = {'state': ['Tamilnadu','telangana','karanataka','goa'], 
        'city': ['Chennai','Hyderabad','Banglore','panaji'], 
         'const': [10,20,30,40], 
         'No_of_school': [100,200,300,105]}
df = pd.DataFrame(dict2, index=[11,12,13,14])

df['No_of_libr'] = pd.Series([15,23,21,14], index=[11,12,13,14])



In [121]:
df[['state', 'city', 'const', 'No_of_school']]

state       city  const  No_of_school
11   Tamilnadu    Chennai     10           100
12   telangana  Hyderabad     20           200
13  karanataka   Banglore     30           300
14         goa     panaji     40           105

In [122]:
df

state       city  const  No_of_school  No_of_libr
11   Tamilnadu    Chennai     10           100          15
12   telangana  Hyderabad     20           200          23
13  karanataka   Banglore     30           300          21
14         goa     panaji     40           105          14

In [164]:
d2={'state':[1,2,3],
    'city':[4,5,6],
    'const':[7,8,9],
    'No_of_school':[10,11,12]}
da1=pd.DataFrame(d2)

dict2 = {'state': ['Tamilnadu','telangana','karanataka'], 
        'city': ['Chennai','Hyderabad','Banglore'], 
         'const': [10,20,30], 
         'No_of_school': [100,200,300]}
df = pd.DataFrame(dict2)


In [165]:
da1

state  city  const  No_of_school
0      1     4      7            10
1      2     5      8            11
2      3     6      9            12

In [166]:
df

state       city  const  No_of_school
0   Tamilnadu    Chennai     10           100
1   telangana  Hyderabad     20           200
2  karanataka   Banglore     30           300

In [167]:
df3 =da1.append(df)


In [168]:
df3 = df3.reset_index(drop=True)
df3


state       city  const  No_of_school
0           1          4      7            10
1           2          5      8            11
2           3          6      9            12
3   Tamilnadu    Chennai     10           100
4   telangana  Hyderabad     20           200
5  karanataka   Banglore     30           300

In [163]:
df3.reset_index?

In [133]:
Markscard= {'Name': ['Sreenath','Pradeep','Arun'],'Science': [50,60,70],'Maths':[70,60,70],'Language': [50,60,80]}
df22= pd.DataFrame(Markscard,index=[10,11,12])
df22


Name  Science  Maths  Language
10  Sreenath       50     70        50
11   Pradeep       60     60        60
12      Arun       70     70        80

In [134]:
df22['School']=pd.Series(['KV','TCIS','DPS'],index=[10,11,12])
Markscard= {'Name': ['Varun','Kumar','Vijay'],'Science': [50,60,70],'Maths':[70,60,70],'Language': [50,60,80]}


In [135]:
df32= pd.DataFrame(Markscard,index=[13,14,15])

In [136]:
df32

Name  Science  Maths  Language
13  Varun       50     70        50
14  Kumar       60     60        60
15  Vijay       70     70        80

In [137]:
df22

Name  Science  Maths  Language School
10  Sreenath       50     70        50     KV
11   Pradeep       60     60        60   TCIS
12      Arun       70     70        80    DPS

In [139]:
df10 = pd.concat([df32, df22])

In [140]:
df10

Name  Science  Maths  Language School
13     Varun       50     70        50    NaN
14     Kumar       60     60        60    NaN
15     Vijay       70     70        80    NaN
10  Sreenath       50     70        50     KV
11   Pradeep       60     60        60   TCIS
12      Arun       70     70        80    DPS

In [ ]:
df['School'] = []

In [143]:
df10.fillna(0)

Name  Science  Maths  Language School
13     Varun       50     70        50      0
14     Kumar       60     60        60      0
15     Vijay       70     70        80      0
10  Sreenath       50     70        50     KV
11   Pradeep       60     60        60   TCIS
12      Arun       70     70        80    DPS

In [141]:
df.fillna?

In [144]:
np.where?

In [152]:
# df10['School'] = np.where(df10['Name'] == 'Varun', 'DPS', df10['School'])
df10['School'] = np.where(df10['Name'] == 'Kumar', 'KV', df10['School'])
df10['School'] = np.where(df10['Name'] == 'Vijay', 'TCIS', df10['School'])

In [153]:
df10

Name  Science  Maths  Language School
13     Varun       50     70        50    DPS
14     Kumar       60     60        60     KV
15     Vijay       70     70        80   TCIS
10  Sreenath       50     70        50     KV
11   Pradeep       60     60        60   TCIS
12      Arun       70     70        80    DPS

In [122]:
dict3={'Age':[25,26,25,23,30,29,23],
       'Name':['Tom','James','Ricky','Vin','Steve','Smith','Jack'],
      'Rating':[4.23,3.24,3.98,2.56,3.20,4.60,3.80]}
df = pd.DataFrame(dict3)



In [123]:
df

Age   Name  Rating
0   25    Tom    4.23
1   26  James    3.24
2   25  Ricky    3.98
3   23    Vin    2.56
4   30  Steve    3.20
5   29  Smith    4.60
6   23   Jack    3.80

In [124]:
df.head()

Age   Name  Rating
0   25    Tom    4.23
1   26  James    3.24
2   25  Ricky    3.98
3   23    Vin    2.56
4   30  Steve    3.20

In [81]:
df.tail()

Age   Name  Rating
2   25  Ricky    3.98
3   23    Vin    2.56
4   30  Steve    3.20
5   29  Smith    4.60
6   23   Jack    3.80

In [82]:
df.T

0      1      2     3      4      5     6
Age       25     26     25    23     30     29    23
Name     Tom  James  Ricky   Vin  Steve  Smith  Jack
Rating  4.23   3.24   3.98  2.56    3.2    4.6   3.8

In [83]:
df

Age   Name  Rating
0   25    Tom    4.23
1   26  James    3.24
2   25  Ricky    3.98
3   23    Vin    2.56
4   30  Steve    3.20
5   29  Smith    4.60
6   23   Jack    3.80

In [84]:
df.axes

[RangeIndex(start=0, stop=7, step=1),
 Index(['Age', 'Name', 'Rating'], dtype='object')]

In [85]:
df.dtypes

Age         int64
Name       object
Rating    float64
dtype: object

In [86]:
df.empty

False

In [87]:
df.shape #dimension

(7, 3)

In [88]:
df.sum()

Age                                  181
Name      TomJamesRickyVinSteveSmithJack
Rating                             25.61
dtype: object

In [89]:
df

Age   Name  Rating
0   25    Tom    4.23
1   26  James    3.24
2   25  Ricky    3.98
3   23    Vin    2.56
4   30  Steve    3.20
5   29  Smith    4.60
6   23   Jack    3.80

In [90]:
df.sum(1)

C:\Users\moham\AppData\Local\Temp/ipykernel_10324/681064937.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.sum(1)


0    29.23
1    29.24
2    28.98
3    25.56
4    33.20
5    33.60
6    26.80
dtype: float64

In [91]:
df.sum(0)

Age                                  181
Name      TomJamesRickyVinSteveSmithJack
Rating                             25.61
dtype: object

In [92]:
import warnings
warnings.filterwarnings('ignore')

In [93]:
df.mean()

Age       25.857143
Rating     3.658571
dtype: float64

In [94]:
df.median()

Age       25.0
Rating     3.8
dtype: float64

In [95]:
df['Age'].mode()

0    23
1    25
dtype: int64

In [96]:
df['Age']

0    25
1    26
2    25
3    23
4    30
5    29
6    23
Name: Age, dtype: int64

In [97]:
df.std()

Age       2.734262
Rating    0.698628
dtype: float64

In [98]:
df

Age   Name  Rating
0   25    Tom    4.23
1   26  James    3.24
2   25  Ricky    3.98
3   23    Vin    2.56
4   30  Steve    3.20
5   29  Smith    4.60
6   23   Jack    3.80

In [99]:
# df.mode()

In [100]:
df.count()

Age       7
Name      7
Rating    7
dtype: int64

In [101]:
df['Age'].min()

23

In [102]:
df['Age'].max()

30

In [103]:
pd.DataFrame(df.describe())

Age    Rating
count   7.000000  7.000000
mean   25.857143  3.658571
std     2.734262  0.698628
min    23.000000  2.560000
25%    24.000000  3.220000
50%    25.000000  3.800000
75%    27.500000  4.105000
max    30.000000  4.600000

In [104]:
dic = {'Col1': [20, 50, 40,  60, 80],
      'Col2': [80, 60, 40, 20, 55],
      'Col3': [20, 80, 55, 66, 33]}

df1 = pd.DataFrame(dic)
df1

Col1  Col2  Col3
0    20    80    20
1    50    60    80
2    40    40    55
3    60    20    66
4    80    55    33

In [105]:
df1.apply(np.mean, axis = 1)

0    40.000000
1    63.333333
2    45.000000
3    48.666667
4    56.000000
dtype: float64

In [106]:
df1.apply(lambda x:x.max() - x.min())

Col1    60
Col2    60
Col3    60
dtype: int64

In [107]:
df1.rename(columns={'Col1': 'Columns1', 'Col2': 'Columns2', 'Col3': 'Columns3'}, inplace=True)

In [108]:
df1

Columns1  Columns2  Columns3
0        20        80        20
1        50        60        80
2        40        40        55
3        60        20        66
4        80        55        33

### Creating the dataframe using random numbers

In [109]:
df = pd.DataFrame(np.random.randn(5, 2), index=[1, 5, 3, 2, 4], columns=['Column1', 'Column2'])
df

Column1   Column2
1  0.727978  0.229897
5 -0.473328 -0.246526
3 -0.680557  1.099073
2 -1.008070 -1.298256
4  0.366410  0.374956

In [110]:
np.random.randn(5)

array([ 0.88411428,  0.56863187,  1.50682314, -0.98847531, -0.36753583])

In [111]:
np.random.randn(5)

array([-0.75597977,  1.26811275,  0.46511108,  1.30123266,  1.35051524])

### Sort the indexes

In [112]:
df.sort_index()

Column1   Column2
1  0.727978  0.229897
2 -1.008070 -1.298256
3 -0.680557  1.099073
4  0.366410  0.374956
5 -0.473328 -0.246526

In [113]:
df.sort_index(ascending=False)


Column1   Column2
5 -0.473328 -0.246526
4  0.366410  0.374956
3 -0.680557  1.099073
2 -1.008070 -1.298256
1  0.727978  0.229897

## Sorting columns

In [114]:
df.sort_index(axis = 1)

Column1   Column2
1  0.727978  0.229897
5 -0.473328 -0.246526
3 -0.680557  1.099073
2 -1.008070 -1.298256
4  0.366410  0.374956

In [115]:
df.sort_values(by = 'Column2', ascending=False)

Column1   Column2
3 -0.680557  1.099073
4  0.366410  0.374956
1  0.727978  0.229897
5 -0.473328 -0.246526
2 -1.008070 -1.298256

In [116]:
df

Column1   Column2
1  0.727978  0.229897
5 -0.473328 -0.246526
3 -0.680557  1.099073
2 -1.008070 -1.298256
4  0.366410  0.374956

### loc - subsetting

In [120]:
df1.loc[:3, ['Age', 'Name']]


KeyError: "None of [Index(['Age', 'Name'], dtype='object')] are in the [columns]"

In [118]:
df.loc[:2,['Age','Name','Rating']]

KeyError: "None of [Index(['Age', 'Name', 'Rating'], dtype='object')] are in the [columns]"

In [119]:
df.head(3)


Column1   Column2
1  0.727978  0.229897
5 -0.473328 -0.246526
3 -0.680557  1.099073

In [38]:
df.loc[:2]


Age   Name  Rating
0   25    Tom    4.23
1   26  James    3.24
2   25  Ricky    3.98

## Changing the index

In [ ]:
df.index = ['a', 'b', 'c', 'd', 'e', 'f', 'g']

In [42]:
df

Age   Name  Rating
a   25    Tom    4.23
b   26  James    3.24
c   25  Ricky    3.98
d   23    Vin    2.56
e   30  Steve    3.20
f   29  Smith    4.60
g   23   Jack    3.80

In [46]:
df.take([0, 1, 2])

Age   Name  Rating
a   25    Tom    4.23
b   26  James    3.24
c   25  Ricky    3.98

In [48]:
df.loc['a':'e',['Age','Name']]


Age   Name
a   25    Tom
b   26  James
c   25  Ricky
d   23    Vin
e   30  Steve

### iloc

In [49]:
df.iloc[:4,:2]

Age   Name
a   25    Tom
b   26  James
c   25  Ricky
d   23    Vin

In [53]:
df.iloc[0:4, 0:2]


Age   Name
a   25    Tom
b   26  James
c   25  Ricky
d   23    Vin

In [54]:
df.iloc[:4]

Age   Name  Rating
a   25    Tom    4.23
b   26  James    3.24
c   25  Ricky    3.98
d   23    Vin    2.56

### Handling the missing data

In [55]:
df1 = pd.DataFrame(np.random.randn(5, 3), index = ['a','c','e','f','h'], columns= ['One', 'Two', 'Three'])
df1

One       Two     Three
a -1.162009  1.032096 -0.268312
c -0.742190  1.854461 -0.631257
e  0.211454  0.202352  1.327111
f -0.664449 -0.616616 -0.062909
h  1.260581  0.347631 -0.035230

In [58]:
df1 = df1.reindex(['a', 'b', 'c', 'd', 'e','f', 'g', 'h'])

In [59]:
df1

One       Two     Three
a -1.162009  1.032096 -0.268312
b       NaN       NaN       NaN
c -0.742190  1.854461 -0.631257
d       NaN       NaN       NaN
e  0.211454  0.202352  1.327111
f -0.664449 -0.616616 -0.062909
g       NaN       NaN       NaN
h  1.260581  0.347631 -0.035230

### Null and notnull functions

In [60]:
df1['Two'].isnull()

a    False
b     True
c    False
d     True
e    False
f    False
g     True
h    False
Name: Two, dtype: bool

In [66]:
df1['One'].notnull()

a     True
b    False
c     True
d    False
e     True
f     True
g    False
h     True
Name: One, dtype: bool

### Filling missing data

In [69]:
df1['One'].fillna(0)

a   -1.162009
b    0.000000
c   -0.742190
d    0.000000
e    0.211454
f   -0.664449
g    0.000000
h    1.260581
Name: One, dtype: float64

In [70]:
df1.fillna(1, inplace=True)
df1

One       Two     Three
a -1.162009  1.032096 -0.268312
b  1.000000  1.000000  1.000000
c -0.742190  1.854461 -0.631257
d  1.000000  1.000000  1.000000
e  0.211454  0.202352  1.327111
f -0.664449 -0.616616 -0.062909
g  1.000000  1.000000  1.000000
h  1.260581  0.347631 -0.035230

In [72]:
df1.loc['d':'f'] = pd.Series({'One':np.NaN, 'Two':np.NaN, 'Three':np.NaN})

In [73]:
df1

One       Two     Three
a -1.162009  1.032096 -0.268312
b  1.000000  1.000000  1.000000
c -0.742190  1.854461 -0.631257
d       NaN       NaN       NaN
e       NaN       NaN       NaN
f       NaN       NaN       NaN
g  1.000000  1.000000  1.000000
h  1.260581  0.347631 -0.035230

In [76]:
df1.dropna()

One       Two     Three
a -1.162009  1.032096 -0.268312
b  1.000000  1.000000  1.000000
c -0.742190  1.854461 -0.631257
g  1.000000  1.000000  1.000000
h  1.260581  0.347631 -0.035230

###  Aggregation

In [125]:
df

Age   Name  Rating
0   25    Tom    4.23
1   26  James    3.24
2   25  Ricky    3.98
3   23    Vin    2.56
4   30  Steve    3.20
5   29  Smith    4.60
6   23   Jack    3.80

In [126]:
df['Score'] = [70,70,80,88,90,95,90]



In [127]:
df

Age   Name  Rating  Score
0   25    Tom    4.23     70
1   26  James    3.24     70
2   25  Ricky    3.98     80
3   23    Vin    2.56     88
4   30  Steve    3.20     90
5   29  Smith    4.60     95
6   23   Jack    3.80     90

In [128]:
df.groupby(['Age'])['Score'].sum()

Age
23    178
25    150
26     70
29     95
30     90
Name: Score, dtype: int64

In [130]:
df.groupby(['Age'])['Score','Rating'].mean().reset_index()


Age  Score  Rating
0   23   89.0   3.180
1   25   75.0   4.105
2   26   70.0   3.240
3   29   95.0   4.600
4   30   90.0   3.200

### Multiple aggregations

In [134]:
df.groupby(['Age'])['Score','Rating'].agg([np.mean, np.median]).reset_index()

Age Score        Rating       
       mean median   mean median
0  23  89.0   89.0  3.180  3.180
1  25  75.0   75.0  4.105  4.105
2  26  70.0   70.0  3.240  3.240
3  29  95.0   95.0  4.600  4.600
4  30  90.0   90.0  3.200  3.200

### Merge -> join

In [136]:
df_left = pd.DataFrame({'Name':['Alex','Amy','Allen','Alice','Ayoung'], 
                        'id':[1,2,3,4,5], 
                        'SubjectId':['Sub1','Sub2','Sub4','Sub6','Sub7']})

df_right = pd.DataFrame({'Name':['Billy','Brian','Bran','Bryce','Betty'],
                         'id':[1,2,3,4,5],
                         'SubjectId':['Sub2','Sub4','Sub3','Sub6','Sub5']})


In [137]:
df_left

Name  id SubjectId
0    Alex   1      Sub1
1     Amy   2      Sub2
2   Allen   3      Sub4
3   Alice   4      Sub6
4  Ayoung   5      Sub7

In [138]:
df_right

Name  id SubjectId
0  Billy   1      Sub2
1  Brian   2      Sub4
2   Bran   3      Sub3
3  Bryce   4      Sub6
4  Betty   5      Sub5

### merge with one key

In [139]:
pd.merge(df_left, df_right, on='id')

Name_x  id SubjectId_x Name_y SubjectId_y
0    Alex   1        Sub1  Billy        Sub2
1     Amy   2        Sub2  Brian        Sub4
2   Allen   3        Sub4   Bran        Sub3
3   Alice   4        Sub6  Bryce        Sub6
4  Ayoung   5        Sub7  Betty        Sub5

In [152]:
df_left

Name  id SubjectId
0    Alex   1      Sub1
1     Amy   2      Sub2
2   Allen   3      Sub4
3   Alice   4      Sub6
4  Ayoung   5      Sub7

In [153]:
df_right

Name  id SubjectId
0  Billy   1      Sub2
1  Brian   2      Sub4
2   Bran   3      Sub3
3  Bryce   4      Sub6
4  Betty   5      Sub5

In [151]:
pd.merge(df_left, df_right, on=['id', 'SubjectId'])

Name_x  id SubjectId Name_y
0  Alice   4      Sub6  Bryce

### Merger operation using 'how'

In [157]:
df_left

Name  id SubjectId
0    Alex   1      Sub1
1     Amy   2      Sub2
2   Allen   3      Sub4
3   Alice   4      Sub6
4  Ayoung   5      Sub7

In [158]:
df_right

Name  id SubjectId
0  Billy   1      Sub2
1  Brian   2      Sub4
2   Bran   3      Sub3
3  Bryce   4      Sub6
4  Betty   5      Sub5

### Left outer join -> how='left'

In [141]:
df_left.merge(df_right, on='SubjectId', how = 'left')

Name_x  id_x SubjectId Name_y  id_y
0    Alex     1      Sub1    NaN   NaN
1     Amy     2      Sub2  Billy   1.0
2   Allen     3      Sub4  Brian   2.0
3   Alice     4      Sub6  Bryce   4.0
4  Ayoung     5      Sub7    NaN   NaN

In [171]:
pd.merge?

### Concat

In [161]:
pd.concat([df_left, df_right], axis=1) #Column wise operation

Name  id SubjectId   Name  id SubjectId
0    Alex   1      Sub1  Billy   1      Sub2
1     Amy   2      Sub2  Brian   2      Sub4
2   Allen   3      Sub4   Bran   3      Sub3
3   Alice   4      Sub6  Bryce   4      Sub6
4  Ayoung   5      Sub7  Betty   5      Sub5

In [162]:
pd.concat([df_left, df_right]) #Row wise operation

Name  id SubjectId
0    Alex   1      Sub1
1     Amy   2      Sub2
2   Allen   3      Sub4
3   Alice   4      Sub6
4  Ayoung   5      Sub7
0   Billy   1      Sub2
1   Brian   2      Sub4
2    Bran   3      Sub3
3   Bryce   4      Sub6
4   Betty   5      Sub5

In [164]:
pd.concat([df_left, df_right], ignore_index = True)

Name  id SubjectId
0    Alex   1      Sub1
1     Amy   2      Sub2
2   Allen   3      Sub4
3   Alice   4      Sub6
4  Ayoung   5      Sub7
5   Billy   1      Sub2
6   Brian   2      Sub4
7    Bran   3      Sub3
8   Bryce   4      Sub6
9   Betty   5      Sub5

In [168]:
df_temp = pd.concat([df_left, df_right])

In [170]:
df_temp.reset_index()

index    Name  id SubjectId
0      0    Alex   1      Sub1
1      1     Amy   2      Sub2
2      2   Allen   3      Sub4
3      3   Alice   4      Sub6
4      4  Ayoung   5      Sub7
5      0   Billy   1      Sub2
6      1   Brian   2      Sub4
7      2    Bran   3      Sub3
8      3   Bryce   4      Sub6
9      4   Betty   5      Sub5

### Append operation to demonstrate the concatenation

In [167]:
df_left.append(df_right, ignore_index = True)

Name  id SubjectId
0    Alex   1      Sub1
1     Amy   2      Sub2
2   Allen   3      Sub4
3   Alice   4      Sub6
4  Ayoung   5      Sub7
5   Billy   1      Sub2
6   Brian   2      Sub4
7    Bran   3      Sub3
8   Bryce   4      Sub6
9   Betty   5      Sub5